name: flutter_jahmaika
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

     # For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
          - assets/images/home_page_background.png
          - assets/images/back.png
          - assets/images/bg_gender_selection.png
          - assets/images/menu_white.png
          - assets/images/shopping_bag_white.png
          - assets/images/bg_style_selection.png
          - assets/images/background_top_collection.png
          - assets/images/image_top_collection.png
          - assets/images/image_top_collection_winter.png
          - assets/images/bg_select_item_type.png
          - assets/images/watch.png
          - assets/images/bag.png
          - assets/images/cloth.png
          - assets/images/footwear.png
          - assets/images/menu_black.png
          - assets/images/shopping_bag_black.png
          - assets/images/img.png
          - assets/images/img_order.png
          - assets/images/triangle_right.png
          - assets/images/close.png
          - assets/images/triangle_down.png
          - assets/images/accesorices.png
          - assets/images/bag_category.png
          - assets/images/books.png
          - assets/images/jewellery.png
          - assets/images/outfits.png
          - assets/images/paintings.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
         - family: avenir
           fonts:
             - asset: assets/fonts/avenir_black.ttf
             - asset: assets/fonts/avenir_book.ttf
             - asset: assets/fonts/avenir_heavy.ttf
             - asset: assets/fonts/avenir_light.ttf
             - asset: assets/fonts/avenir_medium.ttf

         - family: helvetica_neue
           fonts:
              - asset: assets/fonts/helvetica_neue.ttf
              - asset: assets/fonts/helvetica_neue_bold.ttf
              - asset: assets/fonts/helvetica_neue_light.ttf
              - asset: assets/fonts/helvetica_neue_medium.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
